name: Build and test lang-dot package

on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - v2
      - gh-pages
    paths:
      - "packages/lang-dot/**"
      - "package-lock.json"
  workflow_call: {}

permissions:
  contents: read

jobs:
  build:
    name: Build and test lang-dot package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: "Run build and test"
        run: |
          npm clean-install --ignore-scripts
          npm run build
          npm run test
        working-directory: packages/lang-dot

      - uses: actions/upload-artifact@v5
        with:
          name: dist
          path: packages/lang-dot/dist

  test-types:
    name: Test types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: "Install in package directory"
        run: |
          npm clean-install --ignore-scripts
        working-directory: packages/lang-dot

      - name: "Run check-types"
        run: |
          npm clean-install --ignore-scripts
          npm run check-types
        working-directory: packages/lang-dot/test/types
