name: Test website package

on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - v2
      - gh-pages
    paths:
      - "website/**"
  workflow_call: {}

permissions:
  contents: read

jobs:
  build:
    name: Test website package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: "Run tests"
        run: |
          npm clean-install --ignore-scripts
          npm run test
        working-directory: website
