name: Deploy website to GitHub Pages

on:
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: npm clean-install --ignore-scripts
        working-directory: website

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build website
        run: npm run build -- --public-url "${{ steps.pages.outputs.base_path }}/"
        timeout-minutes: 1
        working-directory: website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
